#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xfburn
Version  : 0.5.5
Release  : 3
URL      : http://archive.xfce.org/src/apps/xfburn/0.5/xfburn-0.5.5.tar.bz2
Source0  : http://archive.xfce.org/src/apps/xfburn/0.5/xfburn-0.5.5.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xfburn-bin
Requires: xfburn-data
Requires: xfburn-locales
Requires: xfburn-doc
BuildRequires : exo-dev
BuildRequires : intltool
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gstreamer-pbutils-1.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(libburn-1)
BuildRequires : pkgconfig(libisofs-1)
BuildRequires : pkgconfig(libxfce4ui-1)

%description
==============================================================================
xfburn
------

%package bin
Summary: bin components for the xfburn package.
Group: Binaries
Requires: xfburn-data

%description bin
bin components for the xfburn package.


%package data
Summary: data components for the xfburn package.
Group: Data

%description data
data components for the xfburn package.


%package doc
Summary: doc components for the xfburn package.
Group: Documentation

%description doc
doc components for the xfburn package.


%package locales
Summary: locales components for the xfburn package.
Group: Default

%description locales
locales components for the xfburn package.


%prep
%setup -q -n xfburn-0.5.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1515695644
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1515695644
rm -rf %{buildroot}
%make_install
%find_lang xfburn

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xfburn

%files data
%defattr(-,root,root,-)
/usr/share/Thunar/sendto/thunar-sendto-xfburn.desktop
/usr/share/appdata/xfburn.appdata.xml
/usr/share/applications/xfburn.desktop
/usr/share/icons/hicolor/16x16/stock/media/stock_xfburn-audio-cd.png
/usr/share/icons/hicolor/16x16/stock/media/stock_xfburn-blank-cdrw.png
/usr/share/icons/hicolor/16x16/stock/media/stock_xfburn-burn-cd.png
/usr/share/icons/hicolor/16x16/stock/media/stock_xfburn-data-copy.png
/usr/share/icons/hicolor/16x16/stock/media/stock_xfburn-import-session.png
/usr/share/icons/hicolor/16x16/stock/media/stock_xfburn-new-data-composition.png
/usr/share/icons/hicolor/16x16/stock/media/stock_xfburn.png
/usr/share/icons/hicolor/22x22/stock/media/stock_xfburn-audio-cd.png
/usr/share/icons/hicolor/22x22/stock/media/stock_xfburn-blank-cdrw.png
/usr/share/icons/hicolor/22x22/stock/media/stock_xfburn-burn-cd.png
/usr/share/icons/hicolor/22x22/stock/media/stock_xfburn-data-copy.png
/usr/share/icons/hicolor/22x22/stock/media/stock_xfburn-import-session.png
/usr/share/icons/hicolor/22x22/stock/media/stock_xfburn-new-data-composition.png
/usr/share/icons/hicolor/22x22/stock/media/stock_xfburn.png
/usr/share/icons/hicolor/24x24/stock/media/stock_xfburn-audio-cd.png
/usr/share/icons/hicolor/24x24/stock/media/stock_xfburn-audio-copy.png
/usr/share/icons/hicolor/24x24/stock/media/stock_xfburn-blank-cdrw.png
/usr/share/icons/hicolor/24x24/stock/media/stock_xfburn-burn-cd.png
/usr/share/icons/hicolor/24x24/stock/media/stock_xfburn-data-copy.png
/usr/share/icons/hicolor/24x24/stock/media/stock_xfburn-format-dvdrw.png
/usr/share/icons/hicolor/24x24/stock/media/stock_xfburn-import-session.png
/usr/share/icons/hicolor/24x24/stock/media/stock_xfburn-new-data-composition.png
/usr/share/icons/hicolor/24x24/stock/media/stock_xfburn.png
/usr/share/icons/hicolor/32x32/stock/media/stock_xfburn-audio-cd.png
/usr/share/icons/hicolor/32x32/stock/media/stock_xfburn-blank-cdrw.png
/usr/share/icons/hicolor/32x32/stock/media/stock_xfburn-burn-cd.png
/usr/share/icons/hicolor/32x32/stock/media/stock_xfburn-data-copy.png
/usr/share/icons/hicolor/32x32/stock/media/stock_xfburn-import-session.png
/usr/share/icons/hicolor/32x32/stock/media/stock_xfburn-new-data-composition.png
/usr/share/icons/hicolor/32x32/stock/media/stock_xfburn.png
/usr/share/icons/hicolor/48x48/stock/media/stock_xfburn-audio-cd.png
/usr/share/icons/hicolor/48x48/stock/media/stock_xfburn-blank-cdrw.png
/usr/share/icons/hicolor/48x48/stock/media/stock_xfburn-burn-cd.png
/usr/share/icons/hicolor/48x48/stock/media/stock_xfburn-data-copy.png
/usr/share/icons/hicolor/48x48/stock/media/stock_xfburn-import-session.png
/usr/share/icons/hicolor/48x48/stock/media/stock_xfburn-new-data-composition.png
/usr/share/icons/hicolor/48x48/stock/media/stock_xfburn.png
/usr/share/icons/hicolor/scalable/stock/media/stock_xfburn-audio-cd.svg
/usr/share/icons/hicolor/scalable/stock/media/stock_xfburn-blank-cdrw.svg
/usr/share/icons/hicolor/scalable/stock/media/stock_xfburn-burn-cd.svg
/usr/share/icons/hicolor/scalable/stock/media/stock_xfburn-data-copy.svg
/usr/share/icons/hicolor/scalable/stock/media/stock_xfburn-import-session.svg
/usr/share/icons/hicolor/scalable/stock/media/stock_xfburn-new-data-composition.svg
/usr/share/icons/hicolor/scalable/stock/media/stock_xfburn.svg
/usr/share/xfburn/xfburn-toolbars.ui
/usr/share/xfburn/xfburn.ui

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files locales -f xfburn.lang
%defattr(-,root,root,-)

